version: "3"
services:
  cxedb:
    container_name: cxedb
    image: mongo
    environment:
      - PORT=27017
    volumes:
    - /data-vol:/data/cxedb
      #- /data-vol:/data/cxedb
  cxenode-app:
    container_name: cxenode-app
    restart: always
    build: ./serverapp
    environment:
      - PORT=8002
    links:
      - cxedb
  cxenuxt-app:
    build: ./coinappui
    container_name: cxenuxt-app
    restart: always
    environment:
      - PORT=4001
    command: 'npm run start'